allowBuilds:
  '@swc/core': false
  electron-winstaller: false
  esbuild: false
  fs-xattr: false
  unrs-resolver: false

minimumReleaseAge: 1440

overrides:
  i18n>@messageformat/core: '-'
  xo>eslint-config-xo: ^0.55.0

packageExtensions:
  i18n:
    dependencies:
      intl-messageformat: ^10.7.18

patchedDependencies:
  gatemaker: patches/gatemaker.patch # https://github.com/javan/gatemaker/pull/4
  i18n: patches/i18n.patch # https://github.com/mashpie/i18n-node/pull/546, https://github.com/mashpie/i18n-node/pull/547
