name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Display Node.js version
        run: node --version
      - name: Display npm version
        run: npm --version
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm tests-e2e
